author: Marc Tremblay
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true
      start_line: 1
    span:
      line_numbers: false
markdown: kramdown
plugins:
  - jekyll-feed
show_excerpts: true
social_links:
  github: sapientpants
  rss: sapientpants
  twitter: sapientpants
strict_front_matter: true
timezone: Etc/UTC
title: sapientpants
