about: >-
  Marc Tremblay has been developing software professionally for over 20 years. He is currently an Engineering Lead at BCG Digital Ventures.
author: Marc Tremblay
description: >-
  A blog about engineering and leadership
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true
      start_line: 1
    span:
      line_numbers: false
markdown: kramdown
permalink: /:title/
plugins:
  - jekyll-feed
  - jekyll-sitemap
show_excerpts: true
social_links:
  github: sapientpants
  linkedin: marc-tremblay
  rss: sapientpants
  twitter: sapientpants
strict_front_matter: true
timezone: Etc/UTC
title: sapientpants

# jekyll-seo-tag
social:
  name: Marc Tremblay
  links:
    - https://twitter.com/sapientpants
    - https://www.linkedin.com/in/marc-tremblay
    - https://github.com/sapientpants
tagline: A blog about engineering and leadership
twitter:
  username: sapientpants
  card: summary
