author: Marc Tremblay
description: >-
  Marc Tremblay has been developing software professionally for over 30 years. He is currently an Engineering Lead at BCG Digital Ventures.
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true
      start_line: 1
    span:
      line_numbers: false
markdown: kramdown
plugins:
  - jekyll-feed
show_excerpts: true
social_links:
  github: sapientpants
  keybase: sapientpants
  linkedin: marc-tremblay
  rss: sapientpants
  twitter: sapientpants
strict_front_matter: true
timezone: Etc/UTC
title: sapientpants
